[functions]
  directory = "/src/Netlify"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"
  include = ["BASE_API","WEBSITE_NAME"]